baseURL = "https://stage.psychichomily.com"
environment = "staging"

[params]
environment = "staging"
api_url = "https://stage.api.psychichomily.com"

# Staging-specific parameters
[params.staging]
debug = true
show_draft = true
show_future = true
