[taxonomies]
  venue = "venues"
  band = "bands"
  category = "categories"

[permalinks]
  shows = "/shows/:year/:month/:slug/" 


baseURL = 'https://www.psychichomily.com/'
languageCode = 'en-us'
title = 'Psychic Homily'
theme = 'ananke'

[params]
  mainSections = ["shows", "blog", "venues"]
