baseURL = "https://stage.psychichomily.com"
environment = "stage"
theme = "ananke"

# Inherit all other settings from main config
# This file will be merged with the main hugo.toml
# Only stage-specific overrides are defined here

[params]
environment = "stage"
api_url = "https://stage.api.psychichomily.com"

# Stage-specific parameters
[params.stage]
debug = true
show_draft = true
show_future = true
