package handlers

import (
	"sort"
	"strings"
	"testing"

	"github.com/stretchr/testify/suite"
	"gorm.io/gorm"
)

// TestFixturesAllowlistContractSuite is a CI-enforced check that every table
// with a foreign key to `users` is either (a) in the reset endpoint's
// allowlist, (b) in a documented skip set, or (c) behind a mapped scope
// whose predicate joins through to a user column we do cover.
//
// Why this matters: the reset endpoint's value depends on being exhaustive.
// If a new user-owned table ships and nobody updates the allowlist, tests
// silently leak state for weeks and we only notice when a flake reproduces
// across a long delay. This contract fails CI on the PR that introduces the
// drift.
//
// If you add a new user-FK table, choose one:
//   - Add it to `testFixtureAllowlist` (so tests can reset it), OR
//   - Add it to `testFixturesAllowlistContractSkips` below with a comment
//     explaining why it should NEVER be reset between E2E runs (e.g., audit
//     logs we intentionally preserve, or internal tables whose lifecycle is
//     owned by the backend itself).
type TestFixturesAllowlistContractSuite struct {
	suite.Suite
	deps *handlerIntegrationDeps
}

func TestTestFixturesAllowlistContractSuite(t *testing.T) {
	suite.Run(t, new(TestFixturesAllowlistContractSuite))
}

func (s *TestFixturesAllowlistContractSuite) SetupSuite() {
	s.deps = setupHandlerIntegrationDeps(s.T())
}

// testFixturesAllowlistContractSkips enumerates tables that reference the
// users table but that we DELIBERATELY do NOT reset. Each entry needs a
// one-line justification in code review. If in doubt, add to the allowlist
// instead — resetting too much is safer than too little for E2E.
var testFixturesAllowlistContractSkips = map[string]string{
	// Core identity — users is the root; tests never reset the users table
	// itself, they use per-worker seeded users.
	"users": "per-worker seeded users are reset via their FKs; never truncate users itself",

	// Auth plumbing — not generated by user mutating flows under test.
	"oauth_accounts":        "owned by auth flow; not mutated by E2E scenarios",
	"webauthn_credentials":  "owned by passkey flow; not mutated by E2E scenarios",
	"webauthn_challenges":   "transient, short TTL; backend expires them itself",
	"user_preferences":      "upsert-on-login; resetting would hide regressions",

	// Cross-user behavior + audit — reset would destroy cross-test signal.
	"audit_logs":             "audit trail is intentionally preserved across runs",
	"admin_stats_snapshots":  "aggregate rollups, not user-scoped test artifacts",

	// Comments / field notes — tests clean up via direct DELETE API calls,
	// as called out in the PSY-432 ticket. Keep separate paths.
	"comments":                "cleaned up via direct DELETE API calls per test",
	"comment_edits":           "cascades from comments; handled by comments cleanup",
	"comment_votes":           "cleaned up via direct DELETE in the same test that casts them",
	"comment_subscriptions":   "auto-subscribe flow; cascades from comments",
	"comment_last_reads":      "tracked but not asserted on; re-creation is cheap",

	// Content creation not exercised by the mutating E2E flows we care about.
	"pending_entity_edits":  "entity-edit drawer has its own moderation tests with explicit cleanup",
	"entity_reports":        "report flow has its own tests with explicit cleanup",
	"artist_reports":        "report flow has its own tests with explicit cleanup",
	"show_reports":          "report flow has its own tests with explicit cleanup",
	"api_tokens":            "admin CLI concern; tests use real JWT not tokens",
	"requests":              "requests system has its own tests; pending requests not part of E2E mutating flows",
	"request_votes":         "cascades from requests",
	"field_notes":           "cleaned up via direct DELETE in the show-reflection test",
	"notification_filters":  "preferences-style; upserted, not appended",
	"notification_log":      "sent by background job; not user-mutated in E2E",
	"show_reminders":        "sent by background job; read-only from E2E",
	"enrichment_runs":       "background service writes these; not user-mutated",
	"venue_extraction_runs": "background service writes these; not user-mutated",
	"revisions":             "version history; tests don't assert on the count",
	"auto_promotion_runs":   "background service output; not user-mutated",

	// Tag system — tag create/vote flows aren't currently in the mutating
	// E2E suite. Revisit when we add a tag-mutation smoke test.
	"tags":                     "tag creation not in current E2E mutating flows",
	"tag_votes":                "tag voting not in current E2E mutating flows",
	"entity_tags":              "user-added entity tags not in current E2E mutating flows",
	"artist_relationship_votes": "relationship voting not in current E2E mutating flows",

	// Comment-adjacent naming drift — actual table is `comment_last_read`
	// (singular) not `comment_last_reads`.
	"comment_last_read": "cleaned up by comments' direct DELETE path; naming drift from comment_last_reads",

	// Venues — `submitted_by`/`verified_by` FKs to users exist, but venue
	// submission is not one of the E2E mutating flows we reset. Revisit if
	// that changes.
	"venues": "venue submission not in current E2E mutating flows",

	// Calendar tokens — generated on demand by iCal subscription flow.
	// Unique per user; regenerated if missing.
	"calendar_tokens": "transient per-user tokens; iCal flow regenerates as needed",

	// Profile — preferences-style rows, not test artifacts.
	"user_profile_sections": "preferences-style; upserted, not user-mutated in E2E",
}

// TestAllowlistCoversAllUserFKTables queries information_schema for every
// table with a foreign key column pointing at users, and asserts the table
// is either covered by the reset allowlist or explicitly skipped.
func (s *TestFixturesAllowlistContractSuite) TestAllowlistCoversAllUserFKTables() {
	db := s.deps.db

	userTables, err := tablesWithUsersFK(db)
	s.Require().NoError(err)
	s.Require().NotEmpty(userTables, "information_schema query returned no user-FK tables — query or schema may have drifted")

	covered := make(map[string]bool, len(testFixtureAllowlist))
	for _, scope := range testFixtureAllowlist {
		// The allowlist's display names mostly match physical tables. The
		// one exception is the virtual `pending_shows` scope, which covers
		// the `shows` table (filtered). Map it explicitly here.
		if scope.displayName == "pending_shows" {
			covered["shows"] = true
			continue
		}
		covered[scope.displayName] = true
	}

	// collection_items' FK is `added_by_user_id` — the contract check should
	// accept that. Handled by direct inclusion in the allowlist.
	var missing []string
	for _, tbl := range userTables {
		if covered[tbl] {
			continue
		}
		if _, ok := testFixturesAllowlistContractSkips[tbl]; ok {
			continue
		}
		missing = append(missing, tbl)
	}

	if len(missing) > 0 {
		sort.Strings(missing)
		s.T().Errorf(
			"allowlist drift: the following tables have a FK to users but are neither in testFixtureAllowlist nor in testFixturesAllowlistContractSkips:\n  %s\n\nAdd each to the allowlist OR to the skip map with a justifying comment. See test_fixtures_allowlist_test.go.",
			strings.Join(missing, "\n  "),
		)
	}
}

// tablesWithUsersFK returns the set of tables (other than `users` itself)
// that have a foreign key column referencing `users`.
func tablesWithUsersFK(db *gorm.DB) ([]string, error) {
	rows, err := db.Raw(`
		SELECT DISTINCT tc.table_name
		FROM information_schema.table_constraints tc
		JOIN information_schema.constraint_column_usage ccu
		  ON tc.constraint_name = ccu.constraint_name
		 AND tc.table_schema = ccu.table_schema
		WHERE tc.constraint_type = 'FOREIGN KEY'
		  AND ccu.table_name = 'users'
		  AND tc.table_schema = current_schema()
		ORDER BY tc.table_name
	`).Rows()
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var tables []string
	for rows.Next() {
		var t string
		if err := rows.Scan(&t); err != nil {
			return nil, err
		}
		if t == "users" {
			continue
		}
		tables = append(tables, t)
	}
	return tables, rows.Err()
}
