package auth

import (
	"errors"
	"fmt"
)

// Signed-in home layout (PSY-386): which sections the home page renders and in
// what order. Stored in user_preferences.home_layout as a nullable JSONB
// document; NULL means the shipped default layout, a state a grid of boolean
// columns could not represent (see the migration for why).
//
// This package, not services/user, is the home for the shape and the rules
// because contracts imports models/auth, so both the service that writes the
// document and the handler that rejects a bad one can name the same type.

// HomeLayoutVersion is the only document version this server accepts. It is a
// hard gate rather than a best-effort parse: a newer client's document may
// place meaning in fields this build does not model, and storing it after a
// partial read would silently discard them.
const HomeLayoutVersion = 1

// Section ids. These are a STORAGE CONTRACT shared with the frontend, so they
// are renamed only alongside a migration that rewrites stored documents.
const (
	HomeSectionSavedShows     = "saved_shows"
	HomeSectionNearbyShows    = "nearby_shows"
	HomeSectionCommunityStats = "community_stats"
	HomeSectionCityGraph      = "city_graph"
	HomeSectionRadioShows     = "radio_shows"
)

// knownHomeSections is the whitelist, in shipped default order. The backend is
// the whitelist's single home: an id the server does not know can never be
// rendered, so accepting one would store a section the user can neither see
// nor remove.
//
// A document may omit ids: the frontend appends a missing known section in its
// default slot, which is what lets a section ship without a data migration.
var knownHomeSections = []string{
	HomeSectionSavedShows,
	HomeSectionNearbyShows,
	HomeSectionCommunityStats,
	HomeSectionCityGraph,
	HomeSectionRadioShows,
}

// ErrInvalidHomeLayout marks every rejection below, so one errors.Is at the
// transport boundary separates "the client sent a bad document" (422) from
// "the write failed" (500). The wrapped text says which rule was broken.
var ErrInvalidHomeLayout = errors.New("invalid home layout")

// HomeLayoutSection is one section's placement and visibility. Position in the
// enclosing slice is the placement; a hidden section keeps its slot.
type HomeLayoutSection struct {
	ID      string `json:"id" doc:"Section id: saved_shows, nearby_shows, community_stats, city_graph or radio_shows"`
	Visible bool   `json:"visible" doc:"Whether the section renders"`
}

// HomeLayout is the whole stored document. Replace semantics: a write carries
// every section the user wants placed, and the stored value is exactly what
// the next read returns.
type HomeLayout struct {
	Version  int                 `json:"version" doc:"Document version; must be 1"`
	Sections []HomeLayoutSection `json:"sections" doc:"Sections in render order; a hidden section keeps its slot"`
}

// KnownHomeSections returns the whitelist in shipped default order. It returns
// a copy so a caller cannot reorder the package's own slice.
func KnownHomeSections() []string {
	out := make([]string, len(knownHomeSections))
	copy(out, knownHomeSections)
	return out
}

// Validate reports whether the document may be stored. Every rejection wraps
// ErrInvalidHomeLayout.
//
// The length bound is derived from the whitelist rather than written as its
// own number: with unknown ids and duplicates already rejected, more entries
// than known sections is unreachable, so the check is a guard against a future
// edit loosening one of the other two rules rather than a rule of its own.
func (l *HomeLayout) Validate() error {
	if l == nil {
		return fmt.Errorf("%w: document is missing", ErrInvalidHomeLayout)
	}
	if l.Version != HomeLayoutVersion {
		return fmt.Errorf("%w: unsupported version %d, expected %d",
			ErrInvalidHomeLayout, l.Version, HomeLayoutVersion)
	}
	if len(l.Sections) > len(knownHomeSections) {
		return fmt.Errorf("%w: %d sections exceeds the %d known sections",
			ErrInvalidHomeLayout, len(l.Sections), len(knownHomeSections))
	}

	seen := make(map[string]struct{}, len(l.Sections))
	for _, section := range l.Sections {
		if !isKnownHomeSection(section.ID) {
			return fmt.Errorf("%w: unknown section id %q", ErrInvalidHomeLayout, section.ID)
		}
		if _, duplicate := seen[section.ID]; duplicate {
			return fmt.Errorf("%w: duplicate section id %q", ErrInvalidHomeLayout, section.ID)
		}
		seen[section.ID] = struct{}{}
	}
	return nil
}

// isKnownHomeSection matches an id EXACTLY. No trimming and no case folding:
// the ids are machine-generated by the client, so a value needing repair is a
// client defect, and repairing it here would let two spellings of one section
// both look valid.
func isKnownHomeSection(id string) bool {
	for _, known := range knownHomeSections {
		if id == known {
			return true
		}
	}
	return false
}
