name: PsychicHomily

options:
  bundleIdPrefix: com.psychichomily
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en

settings:
  base:
    SWIFT_VERSION: "6.0"
    GENERATE_INFOPLIST_FILE: true
    SWIFT_STRICT_CONCURRENCY: complete

targets:
  PsychicHomily:
    type: application
    platform: iOS
    sources:
      - path: PsychicHomily
        excludes:
          - Resources/Assets.xcassets
    resources:
      - path: PsychicHomily/Resources/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.psychichomily.ios
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_KEY_CFBundleDisplayName: Psychic Homily
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.music
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: true
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        Release:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: ""
    entitlements:
      path: PsychicHomily/PsychicHomily.entitlements
      properties:
        com.apple.developer.applesignin:
          - Default
        com.apple.security.application-groups:
          - group.com.psychichomily
        keychain-access-groups:
          - $(AppIdentifierPrefix)com.psychichomily.ios
    info:
      path: PsychicHomily/Info.plist
      properties:
        CFBundleURLTypes:
          - CFBundleURLName: com.psychichomily.ios
            CFBundleURLSchemes:
              - psychichomily
        UILaunchScreen:
          UIColorName: phBackground
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    dependencies:
      - target: PsychicHomilyShareExtension

  PsychicHomilyShareExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: PsychicHomilyShareExtension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.psychichomily.ios.share
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_KEY_CFBundleDisplayName: Psychic Homily
    entitlements:
      path: PsychicHomilyShareExtension/PsychicHomilyShareExtension.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.psychichomily
    info:
      path: PsychicHomilyShareExtension/Info.plist
      properties:
        NSExtension:
          NSExtensionPointIdentifier: com.apple.share-services
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).ShareViewController
          NSExtensionAttributes:
            NSExtensionActivationRule:
              NSExtensionActivationSupportsImageWithMaxCount: 1

  PsychicHomilyTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: PsychicHomilyTests
    dependencies:
      - target: PsychicHomily
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.psychichomily.ios.tests
