baseURL = "https://psychichomily.com"
environment = "production"

[params]
environment = "production"
api_url = "https://api.psychichomily.com"

# Production-specific parameters
[params.production]
debug = false
show_draft = false
show_future = false
