-- Fix KEXP show external_ids: the seed migration (000068) used incorrect
-- sequential IDs (1-6) instead of the real KEXP API program IDs.
-- This caused DiscoverShows() to create duplicates instead of matching
-- existing seeded shows.

-- Step 1: Delete any API-discovered duplicate shows that were created because
-- the external_ids didn't match. These duplicates have slugs generated by
-- the upsert (not the seed slugs). We identify them by having the correct
-- API external_id but NOT the seed slug.
-- First, reassign any episodes from duplicates to the canonical seeded show,
-- then delete the duplicates.

-- For each KEXP show, find duplicates by external_id that aren't the seeded slug.
-- We handle this by fixing the seeded shows first, then cleaning up duplicates.

-- Step 1: Fix the external_ids on the seeded KEXP shows (identified by their slug).
UPDATE radio_shows SET external_id = '16'
WHERE slug = 'the-morning-show'
  AND station_id = (SELECT id FROM radio_stations WHERE slug = 'kexp');

UPDATE radio_shows SET external_id = '15'
WHERE slug = 'the-midday-show'
  AND station_id = (SELECT id FROM radio_stations WHERE slug = 'kexp');

UPDATE radio_shows SET external_id = '14'
WHERE slug = 'the-afternoon-show'
  AND station_id = (SELECT id FROM radio_stations WHERE slug = 'kexp');

UPDATE radio_shows SET external_id = '1'
WHERE slug = 'audioasis'
  AND station_id = (SELECT id FROM radio_stations WHERE slug = 'kexp');

UPDATE radio_shows SET external_id = '2'
WHERE slug = 'el-sonido'
  AND station_id = (SELECT id FROM radio_stations WHERE slug = 'kexp');

UPDATE radio_shows SET external_id = '5'
WHERE slug = 'midnight-in-a-perfect-world'
  AND station_id = (SELECT id FROM radio_stations WHERE slug = 'kexp');

-- Step 2: Migrate episodes from duplicate shows to the canonical ones, then
-- delete the duplicates. A duplicate is a show with the same (station_id, external_id)
-- but a different slug than the canonical seeded show.

-- Helper: for each canonical slug + external_id pair, move episodes and delete dupes.
-- We use a CTE approach per show to keep it straightforward.

-- The Morning Show (external_id = '16', canonical slug = 'the-morning-show')
WITH canonical AS (
    SELECT id FROM radio_shows
    WHERE slug = 'the-morning-show'
      AND station_id = (SELECT id FROM radio_stations WHERE slug = 'kexp')
), dupes AS (
    SELECT id FROM radio_shows
    WHERE external_id = '16'
      AND station_id = (SELECT id FROM radio_stations WHERE slug = 'kexp')
      AND slug != 'the-morning-show'
)
UPDATE radio_episodes SET show_id = (SELECT id FROM canonical)
WHERE show_id IN (SELECT id FROM dupes);

DELETE FROM radio_shows
WHERE external_id = '16'
  AND station_id = (SELECT id FROM radio_stations WHERE slug = 'kexp')
  AND slug != 'the-morning-show';

-- The Midday Show (external_id = '15', canonical slug = 'the-midday-show')
WITH canonical AS (
    SELECT id FROM radio_shows
    WHERE slug = 'the-midday-show'
      AND station_id = (SELECT id FROM radio_stations WHERE slug = 'kexp')
), dupes AS (
    SELECT id FROM radio_shows
    WHERE external_id = '15'
      AND station_id = (SELECT id FROM radio_stations WHERE slug = 'kexp')
      AND slug != 'the-midday-show'
)
UPDATE radio_episodes SET show_id = (SELECT id FROM canonical)
WHERE show_id IN (SELECT id FROM dupes);

DELETE FROM radio_shows
WHERE external_id = '15'
  AND station_id = (SELECT id FROM radio_stations WHERE slug = 'kexp')
  AND slug != 'the-midday-show';

-- The Afternoon Show (external_id = '14', canonical slug = 'the-afternoon-show')
WITH canonical AS (
    SELECT id FROM radio_shows
    WHERE slug = 'the-afternoon-show'
      AND station_id = (SELECT id FROM radio_stations WHERE slug = 'kexp')
), dupes AS (
    SELECT id FROM radio_shows
    WHERE external_id = '14'
      AND station_id = (SELECT id FROM radio_stations WHERE slug = 'kexp')
      AND slug != 'the-afternoon-show'
)
UPDATE radio_episodes SET show_id = (SELECT id FROM canonical)
WHERE show_id IN (SELECT id FROM dupes);

DELETE FROM radio_shows
WHERE external_id = '14'
  AND station_id = (SELECT id FROM radio_stations WHERE slug = 'kexp')
  AND slug != 'the-afternoon-show';

-- Audioasis (external_id = '1', canonical slug = 'audioasis')
WITH canonical AS (
    SELECT id FROM radio_shows
    WHERE slug = 'audioasis'
      AND station_id = (SELECT id FROM radio_stations WHERE slug = 'kexp')
), dupes AS (
    SELECT id FROM radio_shows
    WHERE external_id = '1'
      AND station_id = (SELECT id FROM radio_stations WHERE slug = 'kexp')
      AND slug != 'audioasis'
)
UPDATE radio_episodes SET show_id = (SELECT id FROM canonical)
WHERE show_id IN (SELECT id FROM dupes);

DELETE FROM radio_shows
WHERE external_id = '1'
  AND station_id = (SELECT id FROM radio_stations WHERE slug = 'kexp')
  AND slug != 'audioasis';

-- El Sonido (external_id = '2', canonical slug = 'el-sonido')
WITH canonical AS (
    SELECT id FROM radio_shows
    WHERE slug = 'el-sonido'
      AND station_id = (SELECT id FROM radio_stations WHERE slug = 'kexp')
), dupes AS (
    SELECT id FROM radio_shows
    WHERE external_id = '2'
      AND station_id = (SELECT id FROM radio_stations WHERE slug = 'kexp')
      AND slug != 'el-sonido'
)
UPDATE radio_episodes SET show_id = (SELECT id FROM canonical)
WHERE show_id IN (SELECT id FROM dupes);

DELETE FROM radio_shows
WHERE external_id = '2'
  AND station_id = (SELECT id FROM radio_stations WHERE slug = 'kexp')
  AND slug != 'el-sonido';

-- Midnight in a Perfect World (external_id = '5', canonical slug = 'midnight-in-a-perfect-world')
WITH canonical AS (
    SELECT id FROM radio_shows
    WHERE slug = 'midnight-in-a-perfect-world'
      AND station_id = (SELECT id FROM radio_stations WHERE slug = 'kexp')
), dupes AS (
    SELECT id FROM radio_shows
    WHERE external_id = '5'
      AND station_id = (SELECT id FROM radio_stations WHERE slug = 'kexp')
      AND slug != 'midnight-in-a-perfect-world'
)
UPDATE radio_episodes SET show_id = (SELECT id FROM canonical)
WHERE show_id IN (SELECT id FROM dupes);

DELETE FROM radio_shows
WHERE external_id = '5'
  AND station_id = (SELECT id FROM radio_stations WHERE slug = 'kexp')
  AND slug != 'midnight-in-a-perfect-world';

-- Step 3: Also clean up any shows that were created with the OLD wrong external_ids
-- (1-6 mapped to the wrong shows). The seed set external_id='1' for Morning Show,
-- but the API's program 1 is Audioasis. After the DiscoverShows run, the seeded
-- Morning Show (external_id='1') had its name overwritten to "Audioasis". We already
-- fixed the external_id above; now restore the name for the seeded shows.
UPDATE radio_shows SET name = 'The Morning Show'
WHERE slug = 'the-morning-show'
  AND station_id = (SELECT id FROM radio_stations WHERE slug = 'kexp');

UPDATE radio_shows SET name = 'The Midday Show'
WHERE slug = 'the-midday-show'
  AND station_id = (SELECT id FROM radio_stations WHERE slug = 'kexp');

UPDATE radio_shows SET name = 'The Afternoon Show'
WHERE slug = 'the-afternoon-show'
  AND station_id = (SELECT id FROM radio_stations WHERE slug = 'kexp');

UPDATE radio_shows SET name = 'Audioasis'
WHERE slug = 'audioasis'
  AND station_id = (SELECT id FROM radio_stations WHERE slug = 'kexp');

UPDATE radio_shows SET name = 'El Sonido'
WHERE slug = 'el-sonido'
  AND station_id = (SELECT id FROM radio_stations WHERE slug = 'kexp');

UPDATE radio_shows SET name = 'Midnight in a Perfect World'
WHERE slug = 'midnight-in-a-perfect-world'
  AND station_id = (SELECT id FROM radio_stations WHERE slug = 'kexp');

-- Step 4: Add a unique index on (station_id, external_id) to prevent future
-- duplicates at the database level. The upsertRadioShow function already checks
-- this pair, but without a DB constraint, race conditions or bugs can still
-- create duplicates.
CREATE UNIQUE INDEX IF NOT EXISTS idx_radio_shows_station_external_id
ON radio_shows(station_id, external_id)
WHERE external_id IS NOT NULL;
