ALTER TABLE labels DROP COLUMN IF EXISTS image_url;
ALTER TABLE shows DROP COLUMN IF EXISTS image_url;
ALTER TABLE venues DROP COLUMN IF EXISTS image_url;
ALTER TABLE artists DROP COLUMN IF EXISTS image_url;
