/**
 * Regenerate the backend's copy of the affiliate-parameter list from the
 * frontend ticket-vendor table.
 *
 * `frontend/lib/tickets/ticketVendors.ts` is the one place the app writes down
 * which query parameters credit an affiliate. The data-quality console asks the
 * same question of stored `ticket_url` values in SQL, and a second hand-kept
 * list would answer it differently the first time a vendor is added. This
 * script makes the Go side derived output rather than a second list; CI runs it
 * and fails on a diff.
 *
 * Usage: bun run affiliate:params    (from frontend/)
 */

import { KNOWN_AFFILIATE_PARAMS } from '../frontend/lib/tickets/ticketVendors'

const OUT = new URL(
  '../backend/internal/services/admin/affiliate_params_gen.go',
  import.meta.url
)

const params = [...KNOWN_AFFILIATE_PARAMS].sort()

if (params.length === 0) {
  console.error('gen-affiliate-params: the vendor table names no affiliate parameters')
  process.exit(1)
}

for (const param of params) {
  // The generated literal is spliced into a Go regular expression. Anything
  // outside this alphabet would need escaping rules the vendor table has never
  // needed, and inventing them silently is how a predicate stops matching.
  if (!/^[A-Za-z0-9_-]+$/.test(param)) {
    console.error(`gen-affiliate-params: parameter ${JSON.stringify(param)} is not a bare identifier`)
    process.exit(1)
  }
}

const body = `// Code generated by scripts/gen-affiliate-params.ts. DO NOT EDIT.
//
// Source of truth: frontend/lib/tickets/ticketVendors.ts.
// Regenerate with: cd frontend && bun run affiliate:params

package admin

// knownAffiliateParams names every query parameter that credits an affiliate,
// in the spelling a vendor reads.
var knownAffiliateParams = []string{
${params.map(p => `\t${JSON.stringify(p)},`).join('\n')}
}
`

await Bun.write(OUT, body)
console.log(`wrote ${OUT.pathname}`)
