// Code generated by scripts/gen-affiliate-params.ts. DO NOT EDIT.
//
// Source of truth: frontend/lib/tickets/ticketVendors.ts.
// Regenerate with: cd frontend && bun run affiliate:params

package admin

// knownAffiliateParams names every query parameter that credits an affiliate,
// in the spelling a vendor reads.
var knownAffiliateParams = []string{
	"irmp",
}
